-- Authentication and sessions.
--
-- Until now the app resolved "the organisation" by taking the first row, which is a demo shortcut
-- masquerading as multi-tenancy. Tenant context has to come from who is signed in, or row-level
-- security is protecting nothing — the policies were correct but nobody was choosing the tenant.

ALTER TABLE users
  ADD COLUMN password_hash TEXT,
  ADD COLUMN last_login_at TIMESTAMPTZ;

/*
 * Opaque server-side sessions rather than a signed stateless token.
 *
 * A land valuation platform needs revocation that takes effect immediately — an analyst leaves, a
 * laptop is lost, and access has to stop now rather than when a JWT expires. Deleting a row does
 * that; invalidating a signed token needs a denylist, which is a session table with extra steps.
 */
CREATE TABLE sessions (
  -- Random, unguessable, generated by the application. Not sequential and not a UUIDv1.
  id          TEXT PRIMARY KEY,
  user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  -- Which organisation this session is acting within. A user may belong to several; the session
  -- pins one so tenant context is unambiguous on every request.
  organisation_id UUID NOT NULL REFERENCES organisations(id) ON DELETE CASCADE,
  expires_at  TIMESTAMPTZ NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  user_agent  TEXT
);

CREATE INDEX ON sessions (user_id);
CREATE INDEX ON sessions (expires_at);

-- Sessions are read and written only by the auth layer, which runs as owner. The app role must
-- never be able to enumerate sessions — that is a login-as-anyone primitive.
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE sessions FORCE ROW LEVEL SECURITY;
REVOKE ALL ON sessions FROM solum_app;

-- Appraisals gain a name and a re-run lineage, so the platform can show how a view of a plot
-- changed rather than only its latest state. `supersedes` makes the chain explicit rather than
-- inferring it from timestamps.
ALTER TABLE appraisals
  ADD COLUMN supersedes UUID REFERENCES appraisals(id) ON DELETE SET NULL,
  ADD COLUMN note TEXT;

CREATE INDEX ON appraisals (supersedes);
